# Generated by Django 6.0.4 on 2026-05-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_ow_key_to_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
    ]
