# Generated by Django 6.0.4 on 2026-05-10 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_settings_to_practitioner'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name_family',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name_given',
            field=models.CharField(null=True),
        ),
        migrations.CreateModel(
            name='PatientInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=43, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('reissued', 'Reissued'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=16)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_invitations', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.patient')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
